### ISSUE TITLE
Consider adding fallback to files

### ISSUE THREAD

**Issue by shocklateboy92** [memark/zsh-dotnet-completion#1]
It seems the dotnet folks have a better version of the zsh completion script than what they mention in their documentation.

You should take a look and see if it's worth updating yours to match:
https://github.com/dotnet/toolset/blob/master/scripts/register-completions.zsh

**Comment by memark** [comment]
Thank you for bringing this to my attention! @shocklateboy92 

I tried it out a bit. It works better in some aspects, and worse in others. For example:

### better

#### Current
`dotnet Ru<TAB>`
=> dotnet Ru

#### New
`dotnet Ru<TAB>`
=> dotnet run 

(works with commands with incorrect case)

### worse

#### Current
`dotnet build<TAB>`
=> dotnet build

#### New
`dotnet build<TAB>`
=> dotnet BuildStrings

(BuildStrings is not a valid command at all)

Did you try it out? What's your impression?

**Comment by shocklateboy92** [comment]
Odd. I didn't get that behavior. Not even when I put a file called `buildStrings` in the working directory.
