### ISSUE TITLE
Completion is not including files/directories when necessary

### ISSUE THREAD

**Issue by deron-dev** [memark/zsh-dotnet-completion#2]
For example, when I type

```zsh
dotnet sln
```

and press tab, I get

```zsh
-\?                -h                 --help             -s                 
/\?                /h                 --in-root          --solution-folder
```

when I should get something more like

```zsh
lib1/    project1/         solution.sln
```

**Comment by memark** [comment]
Thanks for contributing! @terminal-root 

Yeah, this is not very impressive... Can you please try running `dotnet complete "sln "` and see what that gives you?

I get this
<img width="205" alt="image" src="https://user-images.githubusercontent.com/318504/169758133-6e8496f6-2470-4e6c-addf-00348a33e634.png">

This plugin mostly pipes the result from the CLI to the shell. So if you get the same result, then this is a "feature" of the dotnet CLI itself.

**Comment by deron-dev** [comment]
It seems to be an effect of the CLI itself. Thanks for the reply!
